name: CI

on: [push]

env:
  DEVELOPER_DIR: /Applications/Xcode_11.1.app

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        set -o pipefail
        xcodebuild build -scheme Calcifer -configuration Debug -sdk macosx | xcpretty -c
